#!/usr/bin/env bash
# Interactive setup for OpenClaw Doctor Mini bot. Run on the machine where OpenClaw lives.
set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEFAULT_INSTALL="$HOME/.openclaw/scripts/doctor-bot"
DEFAULT_ENV="$HOME/.openclaw/doctor-bot.env"
DEFAULT_LOG="$HOME/.openclaw/logs"

echo "=== OpenClaw Doctor Mini — setup ==="
echo ""
echo "You need:"
echo "  1. Telegram bot token from @BotFather (/newbot)."
echo "  2. Your Telegram user ID (message @userinfobot or send /start to the bot later and add the ID it shows)."
echo ""

read -r -p "Bot token (e.g. 123456789:ABC...): " BOT_TOKEN
if [[ -z "$BOT_TOKEN" ]]; then
  echo "Token required. Exit."
  exit 1
fi

read -r -p "Allowed user IDs (comma-separated, e.g. 123456789): " ALLOWED_IDS
if [[ -z "$ALLOWED_IDS" ]]; then
  echo "At least one ID required. Exit."
  exit 1
fi

read -r -p "Install directory [$DEFAULT_INSTALL]: " INSTALL_DIR
INSTALL_DIR="${INSTALL_DIR:-$DEFAULT_INSTALL}"
read -r -p "Env file path [$DEFAULT_ENV]: " ENV_FILE
ENV_FILE="${ENV_FILE:-$DEFAULT_ENV}"
read -r -p "Log directory [$DEFAULT_LOG]: " LOG_DIR
LOG_DIR="${LOG_DIR:-$DEFAULT_LOG}"

mkdir -p "$(dirname "$ENV_FILE")"
mkdir -p "$INSTALL_DIR"
mkdir -p "$LOG_DIR"

cat > "$ENV_FILE" << EOF
# Generated by setup.sh — do not commit
DOCTOR_BOT_TOKEN=$BOT_TOKEN
DOCTOR_BOT_ALLOWED_IDS=$ALLOWED_IDS
DOCTOR_BOT_ENV=$ENV_FILE
EOF
chmod 600 "$ENV_FILE"
echo "Wrote $ENV_FILE"

cp "$SCRIPT_DIR/doctor-bot.js" "$INSTALL_DIR/"
cp "$SCRIPT_DIR/run-doctor-bot.sh" "$INSTALL_DIR/"
chmod +x "$INSTALL_DIR/run-doctor-bot.sh"
# Ensure LF line endings
( sed 's/\r$//' "$INSTALL_DIR/run-doctor-bot.sh" > "$INSTALL_DIR/run-doctor-bot.sh.tmp" && mv "$INSTALL_DIR/run-doctor-bot.sh.tmp" "$INSTALL_DIR/run-doctor-bot.sh" ) 2>/dev/null || true
echo "Installed scripts to $INSTALL_DIR"

if [[ "$(uname -s)" == "Darwin" ]]; then
  PLIST="$HOME/Library/LaunchAgents/ai.openclaw.doctor-bot.plist"
  sed -e "s|__INSTALL_DIR__|$INSTALL_DIR|g" -e "s|__LOG_DIR__|$LOG_DIR|g" \
    "$SCRIPT_DIR/ai.openclaw.doctor-bot.plist.template" > "$PLIST"
  echo "Installed LaunchAgent: $PLIST"
  echo ""
  echo "Start: launchctl load $PLIST"
  echo "Stop:  launchctl unload $PLIST"
else
  echo ""
  echo "Linux: run as a service (systemd/supervisor) or: nohup $INSTALL_DIR/run-doctor-bot.sh &"
fi

echo ""
echo "Done. Test: send /start to your bot in Telegram."
